Set-Retweet: Convert to APIv2
thedavecarroll/BluebirdPS pull request #119
Opened 2022-04-26 19:28 UTC by alagoutte

2022-05-01 23:48 UTC, thedavecarroll requested changes
Just a couple things.

Please use PascalCase for properties, parameters, and variables (obviously not API parameters).
Please use the public/api_v2/tweets/ folder.

2022-05-01 23:48 UTC, thedavecarroll commented on BluebirdPS/public/api_v2/Set-Retweet.ps1
> +        $body = @{
Please use PascalCase for properties, parameters, and variables (obviously not API parameters).

`$Body`

2022-05-01 23:48 UTC, thedavecarroll commented on BluebirdPS/public/api_v2/Set-Retweet.ps1
> +            body = ($body | Convertto-json -Depth 10 -Compress)
Please use PascalCase for properties, parameters, and variables.

`Body = ($Body`

2022-05-01 23:48 UTC, thedavecarroll commented on BluebirdPS/public/api_v2/Set-Retweet.ps1
> +function Set-Retweet {
Please move this file to `public/api_v2/tweets`

2022-05-05 06:03 UTC, alagoutte commented on BluebirdPS/public/api_v2/Set-Retweet.ps1
> +        $body = @{
Done

2022-05-05 06:03 UTC, alagoutte commented on BluebirdPS/public/api_v2/Set-Retweet.ps1
> +function Set-Retweet {
Oups, fixed !

2022-05-05 06:12 UTC, merged